# SQLite DB: Storing and Retrieving Vectors

In [27]:
# !pip install sqlite3

import sqlite3
import numpy as np

In [28]:
# create a connection to the SQLite DB
conn = sqlite3.connect('vector-db.db')
# Create a cursor object to execute SQL Commands
cursor = conn.cursor()

In [29]:
# Create a table for vector data
cursor.execute(
"""
CREATE TABLE IF NOT EXISTS vectors (
    id INTEGER PRIMARY KEY,
    vector BLOB NOT NULL
)
"""
)

In [30]:
# generate some sample vectors
vect1 = np.array([1.2, 3.4, 2.1, 0.8])
vect2 = np.array([2.7, 1.5, 3.9, 2.3])

In [31]:
vect1.tobytes() # numpy array to bytestream

b'333333\xf3?333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xe9?'

In [32]:
# Insert vector data into table
cursor.execute("INSERT INTO vectors (vector) VALUES (?)", 
               (sqlite3.Binary(vect1.tobytes()),))


In [33]:
cursor.execute("INSERT INTO vectors (vector) VALUES (?)", 
               (sqlite3.Binary(vect2.tobytes()),))

In [34]:
# Retreive data

cursor.execute("SELECT vector FROM vectors")

In [35]:
rows = cursor.fetchall()

In [36]:
rows

[(b'333333\xf3?333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xe9?',),
 (b'\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\xf8?333333\x0f@ffffff\x02@',)]

In [37]:
vector = np.frombuffer(rows[1][0], dtype = np.float64)

In [38]:
vector

array([2.7, 1.5, 3.9, 2.3])

In [39]:
vectors = []
for row in rows:
    vector = np.frombuffer(row[0], dtype = np.float64)
    vectors.append(vector)

In [40]:
vectors

[array([1.2, 3.4, 2.1, 0.8]), array([2.7, 1.5, 3.9, 2.3])]

# Vector Similarity Search (VSS)

In [41]:
query_vect = np.array([1.0, 3.2, 2.0, 0.5]) 

In [42]:
cursor.execute("""
SELECT vector FROM vectors ORDER BY abs(vector - ?) ASC
""", (sqlite3.Binary(query_vect.tobytes()),))

In [43]:
res = cursor.fetchone()  # finding the top one

In [44]:
np.frombuffer(res[0], dtype=np.float64) # most similar vector

array([2.7, 1.5, 3.9, 2.3])

In [19]:
print(res)

(b'\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\xf8?333333\x0f@ffffff\x02@',)


In [1]:
# !pip install sqlite3

import sqlite3
import numpy as np

In [2]:
# create a connection to the SQLite DB

conn =  sqlite3.connect('vector-db.db')

#create a cursor object to ececute SQL commends

cursor = conn.cursor()

In [3]:
# create a table for vector data

cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS vectors(
    id INTEGER PRIMARY KEY,
    vector BLOB NOT NULL
    )"""
)

In [4]:
# generate some sample vectors

vect1 = np.array([1.2, 3.4, 2.1, 0.8])
vect2 = np.array([2.7, 1.5, 3.9, 2.3])

In [5]:
# vect1
vect1.tobytes()   # numpy array to bytestream

b'333333\xf3?333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xe9?'

In [6]:
# vect2
vect2.tobytes()

b'\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\xf8?333333\x0f@ffffff\x02@'

In [7]:
# insert vector data into table

cursor.execute("INSERT INTO vectors (vector) VALUES (?)",
    (sqlite3.Binary(vect1.tobytes()),)
)

In [8]:
cursor.execute("INSERT INTO vectors (vector) VALUES (?)",
    (sqlite3.Binary(vect2.tobytes()),)
)

In [9]:
# retreive data

cursor.execute("SELECT vector FROM vectors")

In [10]:
rows = cursor.fetchall()

In [11]:
rows

[(b'333333\xf3?333333\x0b@\xcd\xcc\xcc\xcc\xcc\xcc\x00@\x9a\x99\x99\x99\x99\x99\xe9?',),
 (b'\x9a\x99\x99\x99\x99\x99\x05@\x00\x00\x00\x00\x00\x00\xf8?333333\x0f@ffffff\x02@',)]

In [12]:
vector = np.frombuffer(rows[0][0], dtype = np.float64)

In [13]:
vector

array([1.2, 3.4, 2.1, 0.8])

In [14]:
vectors = np.frombuffer(rows[1][0], dtype = np.float64)

In [15]:
vectors

array([2.7, 1.5, 3.9, 2.3])

In [16]:
vectors1 = []
for row in rows:
    vector = np.frombuffer(row[0], dtype = np.float64)
    vectors1.append(vector)

In [17]:
vectors1

[array([1.2, 3.4, 2.1, 0.8]), array([2.7, 1.5, 3.9, 2.3])]

# vector similarity search (VSS)

In [18]:
query_vect = np.array([1.0, 3.2, 2.0, 0.5]) 

In [19]:
cursor.execute("""
SELECT vector FROM vectors ORDER BY abs(vector - ?) ASC
""", (sqlite3.Binary(query_vect.tobytes()),))

In [20]:
res = cursor.fetchone()  # finding the top one

In [21]:
np.frombuffer(res[0], dtype=np.float64) # most similar vector

array([2.7, 1.5, 3.9, 2.3])

In [22]:
print(len(res))

1


In [23]:
conn.close()